---
- name: Listen for events on a webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5050
  rules:
    - name: wait for slack command
      condition: event.payload.command == "/get-diff"
      action:
        run_job_template:
          name: network-eda-backup
          organization: devlab
          job_args:
            extra_vars:
              hosts: "{{ event.payload.text }}"
